# Generated by Django 4.2.7 on 2023-12-15 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_name', models.CharField(max_length=200)),
                ('Post_type', models.CharField(max_length=200)),
                ('Post_title', models.CharField(max_length=100)),
                ('Sub_title', models.CharField(blank=True, max_length=200)),
                ('Description', models.TextField(max_length=500)),
                ('img', models.ImageField(blank=True, upload_to='userimg/')),
                ('Time', models.TimeField(auto_now_add=True)),
                ('view_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='job_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('Type', models.CharField(max_length=200)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('Experiance', models.IntegerField()),
                ('Description', models.TextField(max_length=1800)),
                ('Roles_Responsibiletes', models.TextField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_num', models.BigIntegerField()),
                ('jobtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobposts', to='jobpostapp.job_posts')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('author', models.CharField(max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_jobs', to='jobpostapp.add_job')),
            ],
        ),
    ]
