# Generated by Django 4.2.7 on 2023-12-27 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobpostapp', '0003_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_job',
            name='likes',
            field=models.ManyToManyField(related_name='posted_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
